### PR TITLE
Rebase on Drupal 8.1

### PR DESCRIPTION
**Pull request by bojanz**
- Remove code that was committed to core
- Update tests

TODO: Add the Drupal 8.1 requirement to the composer.json and info.yml

### CODE REVIEW

**Comment by dawehner** [comment]
It would be nice to provide some readme with mappings from the old to the new classnames

**Comment by bojanz** [comment]
I've been unable to get the PR green. No time left.

Locally when I try to access the revision pages I get
"RuntimeException: Callable "Drupal\entity\Access\EntityRevisionRouteAccessChecker::access" requires a value for the "$request" argument. "
Which doesn't match the error on Travis.

@dawehner Please take a look.

**Comment by Berdir** [comment]
Looking a bit at this.

**Comment by Berdir** [comment]
See https://www.drupal.org/node/2688668#comment-10976740

**Comment by Berdir** [comment]
Another problem, this seems to rely on https://www.drupal.org/node/2334319, which is not yet committed.

**Comment by Berdir** [comment]
Pushed some fixes, now this passes for me with the core patch referenced above. Also noticed that \Drupal\Tests\entity\Kernel\RevisionOverviewIntegrationTest is in the wrong directory.

**Comment by agoradesign** [comment]
Added a comment to https://www.drupal.org/node/2334319#comment-10999059 to get clarification, if the core patch still can get into 8.1.x. If yes, we should urgently push this forward, as rc1 is released in less than two weeks.

What are alternatives, if this does not land in 8.1.x? Is a workaround within Entity API possible?

I'm straightly driving into a dependency/patch hell: Commerce will need 8.1.x core, as well as a working Entity API 1.x, planned within the next two weeks

**Comment by agoradesign** [comment]
You also remove the EntityKeysFieldsTrait - what's the correct replacement for this?

**Comment by bojanz** [comment]
@berdir Am I correct in understanding that your commit removed the need for https://www.drupal.org/node/2334319? Or do we still need to add some kind of workaround?

@agoradesign It's now done by ContentEntityBase::baseFieldDefinitions(), entity types just need to call parent::baseFieldDefinitions().

**Comment by agoradesign** [comment]
@bojanz Thanks for the info.. Regarding your other question: I don't think so, that @Berdir removed the need for workaround: 

> Pushed some fixes, now this passes for me with the core patch referenced above. Also noticed that \Drupal\Tests\entity\Kernel\RevisionOverviewIntegrationTest is in the wrong directory.

That's why I added a comment to the core issue today - we need to either bring this into core soon or find a different solution inside Entity API

**Comment by bojanz** [comment]
Actually, the required core patch in question is https://www.drupal.org/node/2688668

**Comment by agoradesign** [comment]
dooooh! then I misunderstood this sorry... Hmm would be really interesing, if we need the other one too

**Comment by Berdir** [comment]
Yes, I did remove the need for that core patch, it works fine without it now.

**Comment by Berdir** [comment]
Yay, finally green.

Haven't reviewed everything but even if it's not perfect, it is certainly better than what we have right now, so lets get it in.

**Pull request merged**
