### PR TITLE
WIP: Add a revision access control handler

### PR DESCRIPTION
**Pull request by dawehner**

### CODE REVIEW

**Comment by bojanz** [comment]
Needs a rebase.

**Comment by dawehner** [comment]
Are you okay with implementing the actual access control handler later?

**Comment by dawehner** [comment]
because well, for example we need to implement the concept of revision access checking first, see other PRs

**Comment by dawehner** [comment]
Blocked on https://github.com/fago/entity/pull/9 I beleive

**Comment by smmccabe** [comment]
Followed the chain down from a Commerce beta blocker, I went to rebase this, but it appears lots/all of this functionality already exists in the main repository so I think the PR is outdated and can be closed?

**Comment by chrfritsch** [comment]
This code already landed in core

**Pull request closed without merging**
